[package]
name = "wavelet-matrix"
version = "0.1.0"
authors = []
edition = "2018"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
succinct-indexable-dictionary = { path = "../succinct-indexable-dictionary" }